FROM node AS build

WORKDIR /app

COPY ./frontend .

RUN npm install
RUN npm run build

FROM nginx:1.25

WORKDIR /var/www/html

COPY ./nginx/nginx.conf /etc/nginx/nginx.conf


COPY --from=build /app/dist ./dist

EXPOSE 443 80