name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm i
      - name: Create .env file
        run: |
          echo API_BASE_URL=${{ secrets.API_BASE_URL }} >> .env.prod
          echo ASSETS_URL=${{ secrets.ASSETS_URL }} >> .env.prod
          echo NO_AUTH_PROTECTION=${{ secrets.NO_AUTH_PROTECTION }} >> .env.prod
          cp .env.prod .env.dev
      - name: Run build
        run: npm run build
      - name: Run dbuild
        run: npm run dbuild
      - name: Check for build and dbuild success
        run: |
          if [ $? -ne 0 ]; then
            echo "Build or dbuild failed with error code $?"
            exit 1
          fi
